# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-19 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciclo', models.IntegerField()),
                ('Nombre_Curso', models.CharField(max_length=60)),
                ('Descripcion_Curso', models.CharField(max_length=120)),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ejer_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.IntegerField()),
                ('Codigo', models.TextField()),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_ej', models.IntegerField()),
                ('Tema_Eje', models.CharField(max_length=120)),
                ('Descripcion_Ej', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Guia', models.CharField(max_length=20)),
                ('Tema_Guia', models.CharField(max_length=120)),
                ('Descripcion_guia', models.CharField(max_length=120)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Guia_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.IntegerField()),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Fecha_Mod', models.DateTimeField(auto_now=True)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Guia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.IntegerField()),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='Guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Guia'),
        ),
        migrations.AddField(
            model_name='ejer_user',
            name='Ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ejercicio'),
        ),
    ]
