# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-11-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejer_user',
            name='Ejercicio',
        ),
        migrations.AddField(
            model_name='ejer_user',
            name='Guia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Guia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejer_user',
            name='Numero_ej',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
