# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20151115_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='Descripcion_guia',
            field=models.TextField(),
        ),
    ]
