# lextab.py. This file automatically created by PLY (version 3.7). Don't edit!
_tabversion   = '3.5'
_lextokens    = set(['COS', 'RETURN', 'COUT', 'DOBLEIGUAL', 'VOID', 'CIN', 'IGUAL', 'CHAR', 'WHILE', 'MENORQUE', 'NUMERAL', 'SIN', 'DISTINTODE', 'ASTERISCO', 'GET', 'POW', 'CORCHETEIZQUIERDO', 'PUNTO', 'LLAVEIZQUIERDA', 'PLUS', 'MENOROIGUAL', 'MAYORQUE', 'TAN', 'ID', 'DIVISION', 'STRINGJC', 'PARENTESISDERECHO', 'STRING', 'FOR', 'NUMBER', 'DOBLEMENORQUE', 'ELSE', 'PARENTESISIZQUIERDO', 'PUNTOYCOMA', 'PORCENTAJE', 'COMA', 'LLAVEDERECHA', 'INCLUDE', 'ENDL', 'IF', 'NAMESPACE_MOD', 'MAS', 'COMILLASDOBLES', 'INT', 'CORCHETEDERECHO', 'SQRT', 'MAYOROIGUAL', 'MENOS', 'DOBLEMAYORQUE', 'MATH', 'MENOSMENOS'])
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_comments>/\\*(.|\\n)*?\\*/)|(?P<t_comments_C99>//(.)*?\\n)|(?P<t_NAMESPACE_MOD>using+[ *]+namespace+[ *]+std)|(?P<t_INCLUDE>include)|(?P<t_COUT>cout)|(?P<t_CIN>cin)|(?P<t_GET>get)|(?P<t_ENDL>endl)|(?P<t_ELSE>else)|(?P<t_IF>if)|(?P<t_INT>int)|(?P<t_STRINGJC>string)|(?P<t_CHAR>char)|(?P<t_RETURN>return)|(?P<t_VOID>void)|(?P<t_WHILE>while)|(?P<t_FOR>for)|(?P<t_POW>pow)|(?P<t_SIN>sin)|(?P<t_COS>cos)|(?P<t_TAN>tan)|(?P<t_SQRT>sqrt)|(?P<t_NUMBER>\\d+)|(?P<t_ID>\\w+(_\\d\\w)*?)|(?P<t_STRING>"[( *?)]+[w+_\\d\\ \\w\\:\\.\\,\\;]*"|"[w+_\\d\\ \\w\\:\\.\\,\\;]*")|(?P<t_MATH>\\.\\h)|(?P<t_NUMERAL>\\#)|(?P<t_PLUS>\\+\\+)|(?P<t_MENOROIGUAL><=)|(?P<t_MAYOROIGUAL>>=)|(?P<t_DIVISION>/)|(?P<t_DOBLEIGUAL>==)|(?P<t_LLAVEIZQUIERDA>{)|(?P<t_LLAVEDERECHA>})|(?P<t_DOBLEMENORQUE>\\<\\<)|(?P<t_DOBLEMAYORQUE>\\>\\>)|(?P<t_DISTINTODE>\\!\\=)|(?P<t_PORCENTAJE>\\%)|(?P<t_newline>\\n+)|(?P<t_MENOSMENOS>\\-\\-)|(?P<t_CORCHETEIZQUIERDO>\\[)|(?P<t_COMILLASDOBLES>\\")|(?P<t_CORCHETEDERECHO>\\])|(?P<t_MAS>\\+)|(?P<t_PUNTO>\\.)|(?P<t_PARENTESISIZQUIERDO>\\()|(?P<t_PARENTESISDERECHO>\\))|(?P<t_ASTERISCO>\\*)|(?P<t_IGUAL>=)|(?P<t_MENOS>-)|(?P<t_MAYORQUE>>)|(?P<t_COMA>,)|(?P<t_PUNTOYCOMA>;)|(?P<t_MENORQUE><)', [None, ('t_comments', 'comments'), None, ('t_comments_C99', 'comments_C99'), None, ('t_NAMESPACE_MOD', 'NAMESPACE_MOD'), ('t_INCLUDE', 'INCLUDE'), ('t_COUT', 'COUT'), ('t_CIN', 'CIN'), ('t_GET', 'GET'), ('t_ENDL', 'ENDL'), ('t_ELSE', 'ELSE'), ('t_IF', 'IF'), ('t_INT', 'INT'), ('t_STRINGJC', 'STRINGJC'), ('t_CHAR', 'CHAR'), ('t_RETURN', 'RETURN'), ('t_VOID', 'VOID'), ('t_WHILE', 'WHILE'), ('t_FOR', 'FOR'), ('t_POW', 'POW'), ('t_SIN', 'SIN'), ('t_COS', 'COS'), ('t_TAN', 'TAN'), ('t_SQRT', 'SQRT'), ('t_NUMBER', 'NUMBER'), ('t_ID', 'ID'), None, ('t_STRING', 'STRING'), ('t_MATH', 'MATH'), ('t_NUMERAL', 'NUMERAL'), ('t_PLUS', 'PLUS'), ('t_MENOROIGUAL', 'MENOROIGUAL'), ('t_MAYOROIGUAL', 'MAYOROIGUAL'), ('t_DIVISION', 'DIVISION'), ('t_DOBLEIGUAL', 'DOBLEIGUAL'), ('t_LLAVEIZQUIERDA', 'LLAVEIZQUIERDA'), ('t_LLAVEDERECHA', 'LLAVEDERECHA'), ('t_DOBLEMENORQUE', 'DOBLEMENORQUE'), ('t_DOBLEMAYORQUE', 'DOBLEMAYORQUE'), ('t_DISTINTODE', 'DISTINTODE'), ('t_PORCENTAJE', 'PORCENTAJE'), ('t_newline', 'newline'), (None, 'MENOSMENOS'), (None, 'CORCHETEIZQUIERDO'), (None, 'COMILLASDOBLES'), (None, 'CORCHETEDERECHO'), (None, 'MAS'), (None, 'PUNTO'), (None, 'PARENTESISIZQUIERDO'), (None, 'PARENTESISDERECHO'), (None, 'ASTERISCO'), (None, 'IGUAL'), (None, 'MENOS'), (None, 'MAYORQUE'), (None, 'COMA'), (None, 'PUNTOYCOMA'), (None, 'MENORQUE')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
